- jubilant/_juju.py
- test/unit/test_basic.py
This PR adds additional arguments for the `deploy` method -- all I think people will use (and possibly more). Design decisions:
- Make the parameter names match the CLI argument names 1:1, even when a plural might make more sense.
- In cases where a str is likely or natural, but a list can also be provided, allow `str | Iterable[str]`.
Also:
- Fix config values when the type is `bool` (should be Go-style lowercase "true" and "false").
- Add docstring "Args:" sections to most methods.
- Simplify `__repr__`.
> fix: add additional params to deploy()

- jubilant/__init__.py
- jubilant/_helpers.py
- jubilant/_juju.py
- jubilant/_types.py
- jubilant/types.py
- pyproject.toml
These come from the Go generator in https://github.com/benhoyt/juju/pull/2 (which now has the `is_*` methods added to `UnitStatus` and `AppStatus`).
Also renames `ApplicationStatus` to `AppStatus` for consistency (we're abbreviating "application" to "app" everywhere).
Fixes #17.
> feat: add generated status dataclasses

- .github/workflows/tests-unit.yaml
Basic GitHub Actions checks. This hasn't been tested -- looks like the `.github` folder must exist on the main branch first, so I'm going to merge early and fix after.
> ci: add GitHub Actions for unit tests, linting, static type checking

- .github/workflows/ci.yaml
- Makefile
- jubilant/_juju.py
I actually introduced GitHub Actions in https://github.com/canonical/jubilant/pull/32 and was going to review there, but GitHub Actions didn't run there because the `.github` directory must exist on `main` first. So I just merged that, and I'm requesting review of the actions YAML on this PR:
**[.github/workflows/tests-unit.yaml](https://github.com/canonical/jubilant/blob/main/.github/workflows/tests-unit.yaml)**
- Example of failing run: https://github.com/canonical/jubilant/actions/runs/13447290839
- Example of succeeding run: https://github.com/canonical/jubilant/actions/runs/13447324561
This PR also changes:
- `tests-unit.yaml` -> `ci.yaml` (one file, at least for now)
- `make fmt` -> `make format`
- `make lint` prints the diff when running the Ruff format check -- when it checks the …
> ci: single ci.yaml, fmt -> format, tweak lint

- jubilant/__init__.py
- jubilant/_actions.py
- jubilant/_juju.py
- jubilant/_yaml.py
- pyproject.toml
- test/unit/test_run.py
- uv.lock
Adds support for the "juju run" command. Don't support `--background` mode or `juju show-operation` for now (likely not needed for integration testing).
This PR adds a dependency on PyYAML, which is kind of inevitable at some point. All params are passed as YAML, to ensure they round trip with the correct types (and to avoid ad-hoc foo.bar=baz serialization on the command line).
I played around with the API design / signature of this for a while. Initially I had an `@overload` that supported the `unit` parameter being either a single unit name a list/tuple of unit names, but the return value was too complex (`ActionResult` in single case, `dict[str, ActionResult]` in the other). We decided to stick with the single-unit version for now, and we can add `run_multiple` or something later. …
> feat: add run method

- .gitignore
- docs/.sphinx/spellingcheck.yaml
Combining two small adjustments:
- Updated the spelling exceptions in `spellingcheck.yaml` to exclude `*emphasised*` text, which is conventionally used when mentioning parameter names. I previously excluded `**bold**` text for a similar reason - the auto generated lists of params wrap the param names in `<strong>` tags (without any other class to identify these elements). I think this approach is fine, as we're unlikely to use emphasised or bold text outside of these contexts in the reference docs.
- Removed `/docs/.sphinx` from the top-level .gitignore file. We can't ignore the whole of the `.sphinx` dir as it has some important files, including `spellingcheck.yaml`. There's a doc-specific .gitignore file inside the `docs` dir.
- Removed `/docs/_build` from the top-level .gitignore file, …
> chore: ignore spelling of params (in *param*) and fix .gitignore

- jubilant/_juju.py
- test/unit/test_add_unit.py
The `attach_storage` and `to` and `num_units` parameters are the same as for `deploy`.
Fixes #5
> feat: add add_unit method

- docs/conf.py
[Version 0.4.0](https://github.com/canonical/canonical-sphinx/releases/tag/0.4.0) of `canonical-sphinx` requires changes in `docs/conf.py` to prevent build warnings:
- Renamed `github_folder` to `repo_folder`
- Renamed `github_version` to `repo_default_branch`
This version of `canonical-sphinx` also makes some changes to the page footers. The following links are gone:
- Discourse and Matrix - We expect people to use "More resources" in the top banner.
- Open a GitHub issue for this page - We expect people to use the "Give feedback" button under the top banner.
- Edit this page on GitHub - Replaced by an optional edit button next to the "Give feedback" button. I've left this disabled for now, but we can enable it in `docs/conf.py` if we like (see 2546c48).
> chore: doc config changes for canonical-sphinx 0.4.0

- .gitignore
- README.md
- jubilant/__init__.py
This adds new sections to the README: basic usage examples, how to contribute/develop the library, and how to do a release. My intention is to flesh out the examples into a real tutorial for the docs online in another PR, but I do want at least something basic in the README.
> docs: flesh out README.md

- docs/.custom_wordlist.txt
- docs/.sphinx/spellingcheck.yaml
- docs/tutorial/getting-started.md
This PR adjusts a few spelling-related things:
- Since we've switched to US English, I changed the dictionary language (in `docs/.sphinx/spellingcheck.yaml`) and removed "favorite" from the list of custom exceptions.
- For MicroK8s, used the official spelling (with a capital K).
- Broadened the rules in `docs/.sphinx/spellingcheck.yaml` so that links to `jubilant.foo` reference docs are always ignored. The text of such links was ignored anyway (because the text uses code formatting), but some link titles were being flagged as spelling errors. That's why we needed to have `AppStatus` and `UnitStatus` in the list of custom exceptions.
> chore: spelling adjustments

- .github/workflows/docs.yaml
- README.md
- docs/tutorial/getting-started.md
This tweaks the docs in two ways (per feedback from @jnsgruk):
* Make the example fixtures in the README and docs *module*-scoped, to match what people are used to with pytest-operator (its fixtures are module-scoped).
* Prominently note the Python 3.12 requirement, as well as how to manage it if your charms are using on older version of Python (older Ubuntu base). I realise this is duplicated, but I think it's important enough to do in both README and docs tutorial.
> docs: make example fixtures module-scoped, explain Python 3.12 requirement

- jubilant/_juju.py
- tests/integration/charms/testdb/src/charm.py
- tests/integration/test_basic.py
- tests/unit/test_run.py
After [testing `juju exec`](https://github.com/canonical/jubilant/pull/66), I wanted to test errors and exceptions with `juju run`. It also needed a try/except to handle the "Uncaught exception in charm code" case, which returns a non-zero exit code and hence raises `CLIError`.
> test: add integration test of run (action) fail and exception

- docs/tutorial/getting-started.md
This PR adds `charmcraft pack` to the sample GitHub action in [Use concierge in CI](https://canonical-jubilant.readthedocs-hosted.com/tutorial/getting-started/#use-concierge-in-ci), as discussed in #68.
> docs: add 'charmcraft pack' in sample GitHub action

- jubilant/_juju.py
- tests/unit/test_deploy.py
This is based on feedback from Jon that the singular is just weird here as it's always a dict, never a single item. I think this is fair, and we don't have to be quite so pedantic about the 1:1 match to the CLI arg.
> fix!: rename deploy param resource -> resources

- README.md
- docs/tutorial/getting-started.md
Juju docs recently moved to documentation.ubuntu.com. This PR updates the two links we have. I considered setting up intersphinx, but it doesn't seem worth it right now.
> docs: change Juju links to point to latest doc site

- Makefile
- jubilant/_juju.py
- tests/integration/test_basic.py
- tests/unit/test_exec.py
- tests/unit/test_run.py
This adds support for the `--wait` argument on the `exec` and `run` methods, allowing you to specify a timeout when waiting for the task.
This PR also adds a `coverage-html` target to the Makefile, and updates the `help` target to show the comment for each target. Thanks James for the idea to use `column` [here](https://github.com/james-garner-canonical/charmlibs-pathops/pull/4/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52). Note also the addition of `MAKEFLAGS += "--always-make"`, avoiding the need for `.PHONY` on all targets.
> feat: add "wait" argument to exec and run

- Makefile
- jubilant/_juju.py
- tests/integration/test_basic.py
- tests/unit/test_remove_relation.py
Add the `Juju.remove_relation` method for removing a relation (the opposite of `integrate`). Type signature is similar to `integrate`.
> feat: add remove_relation method

- jubilant/_juju.py
- tests/integration/test_basic.py
- tests/unit/mocks.py
- tests/unit/test_cli.py
This adds the ability to send standard input to `Juju.cli`, for things like sending Postgres passwords to `scp` and `ssh`.
> feat: add "stdin" parameter to Juju.cli

- jubilant/_juju.py
This PR makes some minor changes to the docstring of `Juju.remove_unit`, for consistency with #86.
> docs: minor rewording in docstring of remove_unit method

- jubilant/_juju.py
- tests/unit/test_remove_unit.py
This PR changes the signature of `Juju.remove_unit` to use `*args` instead of distinguishing between a string or an iterable. This matches the approach for `Juju.exec`.
I've added an extra unit test to guard against an off-by-one error.
> fix!: change remove_unit to use *args

- jubilant/_juju.py
- tests/unit/test_offer.py
- tests/unit/test_wait.py
This PR adds support for `juju offer`.
```python
def offer(self, app: str, *endpoint: str, name: str | None = None) -> None: ...
juju.offer('mysql', 'db', name='offr_name')
```
Fixes #9
> feat: add offer command

- jubilant/_juju.py
- tests/unit/test_wait.py
This removes the logging of every `cli: juju status ...` call while polling status in `Juju.wait` sequences.
Also removes certain "glitches" where it'd show a status change when only `.since` timestamp lines changed, and would result in blank lines like this:
```
INFO wait: status changed:
INFO ... more logs ...
```
Fix #86
> fix: don't log "juju status" calls in Juju.wait()

- jubilant/_juju.py
- tests/integration/test_basic.py
- tests/unit/test_ssh.py
This PR adds support for "juju ssh":
def ssh(
self,
target: str | int,
command: str,
*args: str,
container: str | None = None,
host_key_checks: bool = True,
ssh_options: Iterable[str] = (),
user: str | None = None,
) -> str:
>>> juju.ssh('snappass-test/0', 'echo', 'foo')
'foo\n'
The "user" is a separate argument, not stuffed into the target as on the CLI.
One decision point was the host_key_checks argument. I lean towards what I have here, but we could also do `no_host_key_checks: bool = False`, which is more 1:1 with the CLI. It just felt weird to have an inverted "no_foo" parameter when we can just invert the default in Python.
Fixes #14
> feat: add ssh command

- jubilant/_juju.py
- tests/integration/test_basic.py
- tests/unit/test_refresh.py
This PR adds support for `juju refresh`. The arguments are very similar to `Juju.deploy`.
Nothing too controversial here. The one thing that differs from the CLI is that I've stuffed all the "force_*" arguments under one, so `force=True` becomes `--force --force-base --force-units`. It seems to me that if you want to force and bypass checks, you want to force, and it saves a proliferation of arguments.
def refresh(
self,
app: str,
*,
base: str | None = None,
channel: str | None = None,
config: Mapping[str, ConfigValue] | None = None,
force: bool = False,
path: str | None = None,
resources: Mapping[str, str] | None = None,
revision: int | None = None,
storage: Mapping[str, str] | None = None,
trust: bool = False,
):
>>> juju.refresh('snappass-test')
>>>
Fixes #10
> feat: add refresh command

- jubilant/_juju.py
- jubilant/_task.py
- jubilant/statustypes.py
- tests/unit/test_run.py
- tests/unit/test_task.py
It actually wasn't as bad as I thought in #97, because the default `Exception.__str__` is just the str of the args, so the traceback looked like this:
```
jubilant._task.TaskError: Task(id='42', status='failed', ...)
```
However, this adds a human-readable first line, and pretty-prints the task dataclass:
```
jubilant._task.TaskError: task errror: Task 42, status 'failed', return code 1, details:
Stdout:
STDOUT
Stderr:
STDERR
Message: Some kind of failure
```
Fixes #97
> feat: slightly more helpful TaskError.__str__

- README.md
- docs/how-to/index.md
- docs/how-to/migrate-from-pytest-operator.md
- docs/index.md
- docs/tutorial/getting-started.md
This PR adds a how-to guide with instructions for migration your charm's integration tests from pytest-operator / python-libjuju to Jubilant.
Preview: https://canonical-jubilant--98.com.readthedocs.build/how-to/migrate-from-pytest-operator/
> docs: add "How to migrate from pytest-operator to Jubilant"

- Makefile
- pyproject.toml
- uv.lock
`--always-make` didn't play nicely with `make -C ...`, so fix `make docs` target.
> chore: fix "make docs"; bump up most dependencies

- tests/integration/test_deployment.py
Just adds an integration test for `juju deploy` with `--resource`.
Fixes #75. Most high-level features are covered by integration tests now. Not all arguments, but I think this is enough for now.
> ci: test deploy with resources (and base)

- jubilant/_juju.py
- tests/integration/test_execution.py
- tests/unit/test_deploy.py
- tests/unit/test_refresh.py
- tests/unit/test_scp.py
This PR adds `Juju.scp`, as follows:
```python
def scp(
self,
source: str,
destination: str,
*,
container: str | None = None,
host_key_checks: bool = True,
scp_options: Iterable[str] = (),
) -> None:
```
It's roughly consistent with the existing `ssh` command, though that separates `user` into a separate argument (whereas here `source` and `destination` may have different users, so I don't think it's worth doing that).
Fixes #94
> feat: add scp command

- jubilant/_juju.py
- tests/unit/test_wait.py
This changes the `Juju.wait` "status diff logs" to log under a separate `jubilant.wait` logger, rather than the top-level `jubilant` logger, so that it's easier for users to control them or turn them off separately.
Fixes #104.
> fix: log wait status diffs under jubilant.wait logger name

- docs/how-to/migrate-from-pytest-operator.md
- jubilant/_juju.py
- tests/integration/test_config.py
- tests/unit/test_config.py
- tests/unit/test_model_config.py
This adds support for `juju model-config`: `Juju.model_config`, very similar to the existing `Juju.config` method. I've also added an example of an ops_test-like `fast_forward` context manager.
I don't want to add `fast_forward`, as I don't like it as a practice. I also don't like the name, and it seems too specific. I would consider adding a more general context manager like `jubilant.temp_model_config`, but I think it's better at least for now to leave it to the charms.
Fixes #106.
> feat: add model-config command

- README.md
- docs/how-to/migrate-from-pytest-operator.md
- docs/tutorial/getting-started.md
- jubilant/_all_any.py
- jubilant/_juju.py
- tests/integration/test_execution.py
- tests/unit/test_all_any.py
This is a breaking change to the signature of the `all_*` and `any_*` functions, per discussion at #114: it changes the usage when apps are specified from `all_active(status, ['app1', 'app2'])` to `all_active(status, 'app1', 'app2')` to simplify and provide better ergonomics.
The PR also adds various examples of `juju.wait` with both the direct-callable and lambda usage to make it clearer how you can use these helpers.
Fixes #114.
> fix!: change all_* and any_* to take *apps instead of a list

- jubilant/statustypes.py
- tests/unit/test_statustypes.py
Juju can return the funky `{"status-error": ...}` object as a machine status when a machine is still being set up. This causes the current Jubilant code to raise `StatusError` and fail the test right away. This is not what we want -- we just want `juju.wait()` to wait till the machine has been set up and wait for the status they're looking for, without raising an exception.
We set the status to "failed", which is a [valid Juju status string](https://github.com/juju/juju/blob/5634dd4869129e1bf87e14afb586a28e97078729/core/status/status.go#L109), but unlikely to ever be tested in integration tests. In particular, we don't to use "error", which might need to be distinguished in integration tests, and if people are using `Juju.wait` with `error=jubilant.any_error`, will raise errors -- which …
> fix!: return data rather than raising an exception on status-error

- jubilant/_pretty.py
- jubilant/_test_helpers.py
- tests/integration/conftest.py
- tests/unit/conftest.py
- tests/unit/test_test_helpers.py
To test a CMR in an integration test, it would be great to surface the controller option from the `add_model` method to the `temp_model` method so I can choose whether to deploy the model to LXD or microk8s.
I could manage this manually with juju.add_model, but then I lose the benefit of the automatic teardown.
> feat: deploy a temp model into a specified controller

- jubilant/_juju.py
- tests/integration/test_config.py
- tests/unit/test_config.py
- tests/unit/test_model_config.py
- tests/unit/test_scp.py
- tests/unit/test_ssh.py
This is per our API discussion, to make this a bit clearer/explicit, and more like the Juju CLI.
I needed a third `@overlord` to make the reset-only option work.
> fix!: make "reset" an explicit arg for config/model_config

- jubilant/__init__.py
- jubilant/_juju.py
- tests/unit/test_deploy.py
Fix the format of the `--bind` argument to deploy from comma-separated to space-separated key=value pairs. See [Juju source](https://github.com/juju/juju/blob/214723de24e82f5d14fd255de0885092e0a4dd7c/cmd/juju/application/binding.go#L17-L24).
> fix: fix format of --bind argument for deploy

- .readthedocs.yaml
This PR moves `git fetch ...` to the `post_checkout` job of the RTD build, matching the [latest starter pack](https://github.com/canonical/sphinx-docs-starter-pack/blob/9fc415a52147ea9fcd223a69b690c8b06ca056ab/.readthedocs.yaml#L14-L15). This appears to fix #133 - although I don't fully understand why (it might be coincidence).
> chore: fix Read the Docs builds

- jubilant/_juju.py
- tests/unit/test_add_model.py
Add cloud and credential parameter to `add_model` method. This allows for targeting different clouds on the same controller when creating a model.
Fix: #142
> feat: allow specifying cloud when creating model

- jubilant/_juju.py
- tests/unit/test_offer.py
When implementing the `Juju.offer` method, I had overlooked that that command doesn't take a `--model` argument, and Juju complains when you do. Remove it.
This command doesn't have any integration tests, but update the unit tests with a negative test of this.
Fixes #147.
> fix: "juju model" doesn't use --model argument

- jubilant/_all_any.py
- jubilant/statustypes.py
- tests/unit/fake_statuses.py
- tests/unit/test_all_any.py
- tests/unit/test_statustypes.py
This adds Status.get_units to get an application's units, including the units of subordinate applications. It falls back to `apps[app].units` if the application is a principal (non-subordinate) app.
It also updates the all_* and any_* helpers like all_active and any_error to include units of subordinate apps.
The change to the all_* and any_* helpers is actually a breaking change, though I doubt it will affect users, except in a good way -- it's very likely what they expect already, and the docs say "Report whether any app or unit in status is active" without qualifiers, so it should include the units of subordinate apps.
Fixes #137
> feat: add Status.get_units, include subordinates in all_* and any_*

- .github/workflows/tiobe.yaml
Moving to the self-hosted runners (#167) broke installing the dependencies that the TIOBE "tics" tool requires.
Force installing those as they were before by using `--break-system-packages`.
It would be much better if we were *not* using the system packages (or, ideally, if the tics tool handled installing dependencies itself). It seems like we can activate a venv (like [pgbouncer does](https://github.com/canonical/pgbouncer-operator/blob/main/.github/workflows/tiobe_scan.yaml)), so feel free to push back and suggest doing that. I did try using a venv in some TIOBE work in the past and had difficulty, but there were other issues happening at the time so it may be simple after all. It's unfortunately difficult to test TIOBE workflows unless the branch lives in the organisation repo rather …
> ci: fix installing TIOBE dependencies on the self-hosted runners

- jubilant/_test_helpers.py
- tests/unit/test_test_helpers.py
Allows users to pass the cloud option to jubilant.temp_model for instances with multiple clouds in the same controller, ie testing machine charms integrating with k8s charms.
> feat: have temp_model forward "cloud" and other args to add_model

- README.md
- docs/conf.py
- pyproject.toml
This PR updates hardcoded doc links to point to the new location of the docs: https://documentation.ubuntu.com/jubilant/
I'm also updating the slug, which should avoid unstyled error pages (it seemed to work for Pebble in https://github.com/canonical/pebble/pull/573).
> docs: update links and config for switch to documentation.ubuntu.com/jubilant

- docs/how-to/migrate-from-pytest-operator.md
- docs/tutorial/getting-started.md
As [discussed in Matrix](https://matrix.to/#/!eNCNzcteYUDDYpStsu:ubuntu.com/$wSdesbcVcRYi3t6wKinxcuv7nJ7hLYVW2HDEVP4d4mk), I feel it would be helpful if the tutorial mentions about deploying from `.charm` files vs Charmhub. This PR adds a couple of sentences to do that.
**[Preview doc](https://canonical-ubuntu-documentation-library--187.com.readthedocs.build/jubilant/tutorial/getting-started/#write-a-charm-integration-test)**
> docs: update tutorial with info about deploying .charm files

- jubilant/_juju.py
Every single time I use `wait(timeout=10)` I have to dig through the source code usage to remind myself "10 what"?
> doc: mention 'timeout' argument unit in `wait` method docstring

- docs/how-to/migrate-from-pytest-operator.md
- docs/tutorial/getting-started.md
- jubilant/_juju.py
Now that we have the tutorial (and how-to), there are actually quite a few examples of this, so this only adds one example. But it also shows how to use a stand-alone `def` function with type annotations (which can be better for autocompletion), and links to the examples from the `Juju.wait` reference docs and the migration how-to.
[**Preview**](https://canonical-ubuntu-documentation-library--195.com.readthedocs.build/jubilant/tutorial/getting-started/#use-a-custom-wait-condition)
Fixes #151.
> docs: another wait() example, and link to it from ref and how-to

- jubilant/statustypes.py
This is *definitely* not exhaustive, but it adds docstrings to the top level class and fields, and to many of the second-level classes.
It also adds a module-level docstring describing where these came from (which I'd already forgotten, so good to get this written down :-).
Fixes #138.
> docs: add docstrings to common status classes and attributes

- README.md
- docs/how-to/migrate-from-pytest-operator.md
- docs/tutorial/getting-started.md
- jubilant/__init__.py
- jubilant/_juju.py
- jubilant/statustypes.py
- pyproject.toml
The PR:
* Changes the project name (in this branch) to `jubilant-backports`
* Changes the version (in this branch) to `1.0.0` in preparation of the next release (the latest one from tonyandrewmeyer/jubilant-backports is 1.0.0a1).
* Adjusts the README to reflect the above.
Note that the only differences between the existing jubilant-backports and the current one, in terms of usage, are:
* Instead of `import jubilant_backports as jubilant` you just do `import jubilant`
* `Juju.cli_version` and `Juju.cli_major_version` have been removed.
* The status and task classes are exactly the same types as in `jubilant`, rather than having the same name but being a different class. If anyone was doing something like `jubilant.Status | jubilant_backports.Status` that's not required any more. This does …
> ci: publish the jubilant-backports branch to the jubilant-backports PyPI package

- Makefile
- jubilant/_juju.py
- jubilant/_test_helpers.py
- tests/unit/mocks.py
- tests/unit/test_destroy_model.py
- tests/unit/test_test_helpers.py
The integration-k8s tests are hanging ([example here](https://github.com/canonical/jubilant/actions/runs/17312074131/job/49297452945)) just after the second-to-last test (test_secrets.test_get_all_secrets) and then timing out after 6h. Juju hangs on cleanup -- after talking to the Juju team, this is a Microk8s issue, so work around it here.
We could only do this for microk8s, but it seems like when using a temp model, destroying it should never take longer than a reasonable time (10 minutes seems ample), so just add a timeout to the `juju destroy-model` in `temp_model()` always.
> fix: add timeout to temp_model destroy-model to fix microk8s issues

- .github/workflows/publish.yaml
- README.md
Explain what feature set is supported, and update the tag instructions for publishing. Also adjust a bit of language that was more correct with the old tonyandrewmeyer/jubilant-backports.
[Read the full README with the changes here](https://github.com/canonical/jubilant/blob/tonyandrewmeyer-patch-1/README.md).
> docs: README tweaks, particularly for publishing
